module:
  imports:
  - path: ../../node_modules/@fortawesome/fontawesome-free
    ignoreConfig: true
    disable: false
    mounts:
    - source: svgs
      target: assets/svg/fa-svgs
  - path: ../../node_modules/clipboard
    ignoreConfig: true
    disable: false
    mounts:
    - source: dist
      target: assets/js
  - path: ../../node_modules/iframe-resizer
    ignoreConfig: true
    disable: false
    mounts:
    - source: js
      target: assets/js

menu:
  main:
  - name: Notes 
    weight: 10
    pre: <i class='fas fa-2x fa-file-alt'></i>
    url: /app/notes/
  - name: Flow
    weight: 30
    pre: <i class='fas fa-2x fa-list-ul'></i>
    url: /flow/
  - name: Literature
    weight: 20
    pre: <i class='fas fa-2x fa-book'></i>
    url: /app/literature/
  - name: Diary
    weight: 40
    pre: <i class='fas fa-2x fa-feather-alt'></i>
    url: /app/diary/

  # also add netlifycms to package.json before activating (!Build time expensive)
  # - path: ../../node_modules/netlify-cms
  #   ignoreConfig: true
  #   disable: false  
  #   mounts:
  #   - source: dist
  #     target: assets/js/netlify