site_url: {{.Site.Home.Permalink}}
display_url: {{.Site.Home.Permalink}}

{{ $logo := resources.Get (printf "svg/%s.svg" "thought-tank-logo-color")  | resources.Minify }}
logo_url: {{ $logo.Permalink }}

backend:
  name: {{ .Site.Params.backend.name }}
  repo: {{ .Site.Params.backend.repo }}
  branch: {{ .Site.Params.backend.branch }}
  commit_messages:
    create: Create {{print "{{collection}}"}} "{{print "{{slug}}"}}"
    update: Update {{print "{{collection}}"}} "{{print "{{slug}}"}}"
    delete: Delete {{print "{{collection}}"}} "{{print "{{slug}}"}}"

