site_url: {{.Site.Home.Permalink}}
display_url: {{.Site.Home.Permalink}}

{{ $logo := resources.Get (printf "svg/%s.svg" "thought-tank-logo-color")  | resources.Minify }}
logo_url: {{ $logo.Permalink }}

backend:
  name: {{ .Site.Params.backend.name | default "github"}}
  {{/* Netlify Repository environment variable comes with protocol and domain */}}
  repo: {{ (urls.Parse .Site.Params.backend.repo).Path | strings.TrimPrefix "/" }}
  branch: {{ .Site.Params.backend.branch }}
  commit_messages:
    create: Create {{print "{{collection}}"}} "{{print "{{slug}}"}}"
    update: Update {{print "{{collection}}"}} "{{print "{{slug}}"}}"
    delete: Delete {{print "{{collection}}"}} "{{print "{{slug}}"}}"

